FROM @REPO@/kube-builder:latest AS builder

FROM alpine:@ALPINE_VERSION@

RUN apk upgrade --update --no-cache \
	&& groupadd -g 160 kube-apisever \
	&& useradd -g 160 -u 160 -r kube-apiserver

USER kube-apiserver

COPY --from=builder /kube-apiserver /
