FROM @REPO@/kube-builder:latest AS builder

FROM alpine:@ALPINE_VERSION@

LABEL name="kube-controller-manager" \
	version="@VERSION@" \
	release="0" \
	architecture="x86_v64" \
	atomic.type="system" \
	summary="the Kubernetes controller-manager daemon" \
	maintainer="Dan Molik <dan@whisperos.org>"

RUN apk update --upgrade --no-cache

COPY --from=builder /kube-controller-manager /

ENTRYPOINT /kube-controller-manager
