FROM @REPO@/kube-builder:latest AS builder

FROM alpine:@ALPINE_VERSION@

LABEL name="kube-apiserver" \
	version="@VERSION@" \
	release="0" \
	architecture="x86_v64" \
	atomic.type="system" \
	summary="the Kubernetes api-server daemon"
	maintainer="Dan Molik <dan@whisperos.org>"

RUN apk upgrade --update --no-cache

USER kube-apiserver

COPY --from=builder /kube-apiserver /
