FROM @REPO@/etcd-builder:latest AS builder

FROM alpine:@ALPINE_VERSION@

RUN apk upgrade --update --no-cache \
	&& addgroup -S -g 159 etcd \
	&& adduser  -S -g 159 -u 159 -G etcd -s /sbin/nologin etcd

USER etcd

COPY --from=builder /build/etcd /
