FROM @REPO@/etcd-builder:latest AS builder

FROM alpine:@ALPINE_VERSION@

LABEL name="etcd" \
	version="@VERSION@" \
	release="0" \
	architecture="x86_v64" \
	atomic.type="system" \
	summary="Etcd distributed reliable k/v datastore" \
	maintainer="Dan Molik <dan@whisperos.org>"

RUN apk upgrade --update --no-cache

COPY --from=builder /build/etcd /
COPY --from=builder /build/etcdctl /

ENTRYPOINT /etcd
